export const frontendProjects = [
  {
    Ptitle: "Ecommerce_App",
    category: ["React"],
    Pdescription: `A full eCommerce platform with authentication, product browsing, cart features, responsive layout, and smooth user experience across all devices.`,
    iconlink: "https://ecommerce-app-nu-five.vercel.app/",
    iconGithub: "https://github.com/Mohamerabee98/Ecommerce-App",
    imgPath: "./1.webp",
  },
  {
    Ptitle: "DevCode",
    category: ["React"],
    Pdescription: `A modern company website showcasing technical services, clean interface, smooth animations, interactive sections, and professional presentation of team expertise.`,
    iconlink: "https://devcode-21.web.app/",
    iconGithub: "https://github.com/Mohamerabee98/DevCode",
    imgPath: "./26.webp",
  },
  {
    Ptitle: "MASAR company",
    category: ["js", "bootstrap"],
    Pdescription: `A digital solutions website offering web design, mobile applications, eCommerce services, branding, and social media management for businesses.`,
    iconlink: "https://github.com/Mohamerabee98/MASAR",
    iconGithub: "https://github.com/Mohamerabee98/MASAR",
    imgPath: "./20.webp",
  },
  {
    Ptitle: "TO DO LIST",
    category: ["js", "css"],
    Pdescription: `A simple and responsive task management app allowing users to create, edit, delete, and complete daily tasks easily.`,
    iconlink: "https://mohamerabee98.github.io/TO-DO-LIST2/",
    iconGithub: "https://github.com/Mohamerabee98/TO-DO-LIST2",
    imgPath: "./22.webp",
  },
  {
    Ptitle: "Simple Ecommecre",
    category: ["React", "Next"],
    Pdescription: `A CRUD-based application built using Next.js enabling users to create, read, update, and delete products efficiently.`,
    iconlink: "https://github.com/Mohamerabee98/Crud-operator-nextjs",
    iconGithub: "https://github.com/Mohamerabee98/Crud-operator-nextjs",
    imgPath: "./21.webp",
  },
  {
    Ptitle: "CRUD System ",
    category: ["js"],
    Pdescription: `A complete CRUD system providing smooth data management, responsive layout, clean interactions, and a simple user-friendly interface.`,
    iconlink: "https://mohamerabee98.github.io/Crud-System/",
    iconGithub: "https://github.com/Mohamerabee98/Crud-System",
    imgPath: "./4.webp",
  },
  {
    Ptitle: "Special Design ",
    category: ["js"],
    Pdescription: `An interactive JavaScript project demonstrating animations, form handling, dynamic behavior, and responsive design for engaging web applications.`,
    iconlink: "https://mohamerabee98.github.io/Project_Js/",
    iconGithub: "https://github.com/Mohamerabee98/Project_Js",
    imgPath: "./2.webp",
  },
  {
    Ptitle: "Medherball Company",
    category: ["React"],
    Pdescription: `An online store providing natural supplements focused on weight loss, health improvement, safe ingredients, and smooth shopping experience.`,
    iconlink: "https://medherball.web.app/",
    iconGithub: "https://medherball.web.app/",
    imgPath: "./23.webp",
  },
  {
    Ptitle: "lamsa-Daewish",
    category: ["js", "bootstrap"],
    Pdescription: `A professional services website offering interior and exterior finishing, decoration, painting, plumbing, and electrical solutions for clients.`,
    iconlink: "https://lamsa-darwish.netlify.app/",
    iconGithub: "https://github.com/Mohamerabee98/Baitak",
    imgPath: "./24.webp",
  },
  {
    Ptitle: "Food delivers",
    category: ["React", "js"],
    Pdescription: `A food delivery website offering organic honey and natural products with trusted sourcing, quality assurance, and customer satisfaction.`,
    iconlink: "https://morabeefood.netlify.app/",
    iconGithub: "https://morabeefood.netlify.app/",
    imgPath: "./25.webp",
  },
];

export const backendProjects = [
  {
    Ptitle: "Blog API",
    category: ["Express", "Sequelize"],
    Pdescription: `A scalable blog backend supporting CRUD operations using RESTful APIs with clean MVC structure and MySQL database.`,
    iconlink: "https://github.com/Mohamerabee98/blog_app_Sequelize",
    iconGithub: "https://github.com/Mohamerabee98/blog_app_Sequelize",
    imgPath: "./blog.webp",
  },
  {
    Ptitle: "Pharmacy-Management-System",
    category: ["Node", "Express"],
    Pdescription: `A pharmacy backend system managing products, users, and sales with role-based access and secure stock operations.`,
    iconlink: "https://github.com/Mohamerabee98/Pharmacy-Management-System",
    iconGithub: "https://github.com/Mohamerabee98/Pharmacy-Management-System",
    imgPath: "./pharmacy_System.webp",
  },
  {
    Ptitle: "Saraha-App",
    category: ["Node", "Express"],
    Pdescription: `An anonymous messaging backend API with authentication, secure communication, RESTful routes, and scalable architecture design.`,
    iconlink: "https://github.com/Mohamerabee98/Saraha-App",
    iconGithub: "https://github.com/Mohamerabee98/Saraha-App",
    imgPath: "./Saraha.webp",
  },
];
